//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/weaviate/weaviate/entities/models"
)

// SchemaObjectsCopyshardHandlerFunc turns a function with the right signature into a schema objects copyshard handler
type SchemaObjectsCopyshardHandlerFunc func(SchemaObjectsCopyshardParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SchemaObjectsCopyshardHandlerFunc) Handle(params SchemaObjectsCopyshardParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SchemaObjectsCopyshardHandler interface for that can handle valid schema objects copyshard params
type SchemaObjectsCopyshardHandler interface {
	Handle(SchemaObjectsCopyshardParams, *models.Principal) middleware.Responder
}

// NewSchemaObjectsCopyshard creates a new http.Handler for the schema objects copyshard operation
func NewSchemaObjectsCopyshard(ctx *middleware.Context, handler SchemaObjectsCopyshardHandler) *SchemaObjectsCopyshard {
	return &SchemaObjectsCopyshard{Context: ctx, Handler: handler}
}

/*
	SchemaObjectsCopyshard swagger:route POST /schema/{className}/copyshard schema schemaObjectsCopyshard

Copy a shard from one node to another TODO real name/etc

Copy a shard from one node to another
*/
type SchemaObjectsCopyshard struct {
	Context *middleware.Context
	Handler SchemaObjectsCopyshardHandler
}

func (o *SchemaObjectsCopyshard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSchemaObjectsCopyshardParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
