//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// SchemaObjectsCopyshardReader is a Reader for the SchemaObjectsCopyshard structure.
type SchemaObjectsCopyshardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchemaObjectsCopyshardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchemaObjectsCopyshardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSchemaObjectsCopyshardUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSchemaObjectsCopyshardForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSchemaObjectsCopyshardUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSchemaObjectsCopyshardInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSchemaObjectsCopyshardOK creates a SchemaObjectsCopyshardOK with default headers values
func NewSchemaObjectsCopyshardOK() *SchemaObjectsCopyshardOK {
	return &SchemaObjectsCopyshardOK{}
}

/*
SchemaObjectsCopyshardOK describes a response with status code 200, with default header values.

Shard was copied successfully
*/
type SchemaObjectsCopyshardOK struct {
}

// IsSuccess returns true when this schema objects copyshard o k response has a 2xx status code
func (o *SchemaObjectsCopyshardOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this schema objects copyshard o k response has a 3xx status code
func (o *SchemaObjectsCopyshardOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this schema objects copyshard o k response has a 4xx status code
func (o *SchemaObjectsCopyshardOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this schema objects copyshard o k response has a 5xx status code
func (o *SchemaObjectsCopyshardOK) IsServerError() bool {
	return false
}

// IsCode returns true when this schema objects copyshard o k response a status code equal to that given
func (o *SchemaObjectsCopyshardOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the schema objects copyshard o k response
func (o *SchemaObjectsCopyshardOK) Code() int {
	return 200
}

func (o *SchemaObjectsCopyshardOK) Error() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardOK ", 200)
}

func (o *SchemaObjectsCopyshardOK) String() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardOK ", 200)
}

func (o *SchemaObjectsCopyshardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSchemaObjectsCopyshardUnauthorized creates a SchemaObjectsCopyshardUnauthorized with default headers values
func NewSchemaObjectsCopyshardUnauthorized() *SchemaObjectsCopyshardUnauthorized {
	return &SchemaObjectsCopyshardUnauthorized{}
}

/*
SchemaObjectsCopyshardUnauthorized describes a response with status code 401, with default header values.

Unauthorized or invalid credentials.
*/
type SchemaObjectsCopyshardUnauthorized struct {
}

// IsSuccess returns true when this schema objects copyshard unauthorized response has a 2xx status code
func (o *SchemaObjectsCopyshardUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this schema objects copyshard unauthorized response has a 3xx status code
func (o *SchemaObjectsCopyshardUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this schema objects copyshard unauthorized response has a 4xx status code
func (o *SchemaObjectsCopyshardUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this schema objects copyshard unauthorized response has a 5xx status code
func (o *SchemaObjectsCopyshardUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this schema objects copyshard unauthorized response a status code equal to that given
func (o *SchemaObjectsCopyshardUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the schema objects copyshard unauthorized response
func (o *SchemaObjectsCopyshardUnauthorized) Code() int {
	return 401
}

func (o *SchemaObjectsCopyshardUnauthorized) Error() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardUnauthorized ", 401)
}

func (o *SchemaObjectsCopyshardUnauthorized) String() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardUnauthorized ", 401)
}

func (o *SchemaObjectsCopyshardUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSchemaObjectsCopyshardForbidden creates a SchemaObjectsCopyshardForbidden with default headers values
func NewSchemaObjectsCopyshardForbidden() *SchemaObjectsCopyshardForbidden {
	return &SchemaObjectsCopyshardForbidden{}
}

/*
SchemaObjectsCopyshardForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SchemaObjectsCopyshardForbidden struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this schema objects copyshard forbidden response has a 2xx status code
func (o *SchemaObjectsCopyshardForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this schema objects copyshard forbidden response has a 3xx status code
func (o *SchemaObjectsCopyshardForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this schema objects copyshard forbidden response has a 4xx status code
func (o *SchemaObjectsCopyshardForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this schema objects copyshard forbidden response has a 5xx status code
func (o *SchemaObjectsCopyshardForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this schema objects copyshard forbidden response a status code equal to that given
func (o *SchemaObjectsCopyshardForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the schema objects copyshard forbidden response
func (o *SchemaObjectsCopyshardForbidden) Code() int {
	return 403
}

func (o *SchemaObjectsCopyshardForbidden) Error() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardForbidden  %+v", 403, o.Payload)
}

func (o *SchemaObjectsCopyshardForbidden) String() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardForbidden  %+v", 403, o.Payload)
}

func (o *SchemaObjectsCopyshardForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SchemaObjectsCopyshardForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchemaObjectsCopyshardUnprocessableEntity creates a SchemaObjectsCopyshardUnprocessableEntity with default headers values
func NewSchemaObjectsCopyshardUnprocessableEntity() *SchemaObjectsCopyshardUnprocessableEntity {
	return &SchemaObjectsCopyshardUnprocessableEntity{}
}

/*
SchemaObjectsCopyshardUnprocessableEntity describes a response with status code 422, with default header values.

Invalid request
*/
type SchemaObjectsCopyshardUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this schema objects copyshard unprocessable entity response has a 2xx status code
func (o *SchemaObjectsCopyshardUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this schema objects copyshard unprocessable entity response has a 3xx status code
func (o *SchemaObjectsCopyshardUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this schema objects copyshard unprocessable entity response has a 4xx status code
func (o *SchemaObjectsCopyshardUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this schema objects copyshard unprocessable entity response has a 5xx status code
func (o *SchemaObjectsCopyshardUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this schema objects copyshard unprocessable entity response a status code equal to that given
func (o *SchemaObjectsCopyshardUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the schema objects copyshard unprocessable entity response
func (o *SchemaObjectsCopyshardUnprocessableEntity) Code() int {
	return 422
}

func (o *SchemaObjectsCopyshardUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *SchemaObjectsCopyshardUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *SchemaObjectsCopyshardUnprocessableEntity) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SchemaObjectsCopyshardUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchemaObjectsCopyshardInternalServerError creates a SchemaObjectsCopyshardInternalServerError with default headers values
func NewSchemaObjectsCopyshardInternalServerError() *SchemaObjectsCopyshardInternalServerError {
	return &SchemaObjectsCopyshardInternalServerError{}
}

/*
SchemaObjectsCopyshardInternalServerError describes a response with status code 500, with default header values.

An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.
*/
type SchemaObjectsCopyshardInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this schema objects copyshard internal server error response has a 2xx status code
func (o *SchemaObjectsCopyshardInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this schema objects copyshard internal server error response has a 3xx status code
func (o *SchemaObjectsCopyshardInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this schema objects copyshard internal server error response has a 4xx status code
func (o *SchemaObjectsCopyshardInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this schema objects copyshard internal server error response has a 5xx status code
func (o *SchemaObjectsCopyshardInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this schema objects copyshard internal server error response a status code equal to that given
func (o *SchemaObjectsCopyshardInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the schema objects copyshard internal server error response
func (o *SchemaObjectsCopyshardInternalServerError) Code() int {
	return 500
}

func (o *SchemaObjectsCopyshardInternalServerError) Error() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardInternalServerError  %+v", 500, o.Payload)
}

func (o *SchemaObjectsCopyshardInternalServerError) String() string {
	return fmt.Sprintf("[POST /schema/{className}/copyshard][%d] schemaObjectsCopyshardInternalServerError  %+v", 500, o.Payload)
}

func (o *SchemaObjectsCopyshardInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SchemaObjectsCopyshardInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
